name: Build and Compress Go Application on MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build the application
      shell: bash
      run: |
        sed -i '' 's/AppId.*=.*".*"/AppId = "${{ secrets.AppId }}"/' main.go
        sed -i '' 's/AppSecret.*=.*".*"/AppSecret = "${{ secrets.AppSecret }}"/' main.go
        go build -ldflags="-s -w" -o bin/dandanplay main.go
        rm -f main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dandanplay
        path: bin/dandanplay
