name: Build and Test Go Application on Windows

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install UPX
      run: choco install upx
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build the application
      run: |
        (Get-Content -Path .\main.go) -replace 'AppId\s*=\s*".*"', 'AppId = "${{ secrets.AppSecret }}"' -replace 'AppSecret\s*=\s*".*"', 'AppSecret = "${{ secrets.AppSecret }}"' | Set-Content -Path .\main.go
        go build -ldflags="-s -w" -o bin/curl_wrapper.exe main.go

    - name: Compress with UPX
      run: upx --best --lzma -o bin/dandanplay.exe bin/curl_wrapper.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dandanplay
        path: bin/dandanplay.exe
